apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: kotlinknativefunction
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: docker.io/timriemer/kotlinknativefunction
          env:
            - name: WORLD
              value: "World!"
